
<script setup>

</script>

<template>
    <div class="flex flex-row min-w-full justify-around mt-20">
        <div class=" w-96 bg-red-300"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptate commodi temporibus, maxime omnis, magni cumque non excepturi dolorem, quisquam quidem ad nihil repellendus odio consectetur mollitia. Quia tempora, libero ipsa commodi repellat atque doloribus, totam labore nihil deleniti ex eum maiores culpa fugit assumenda, molestiae obcaecati sapiente sequi. Dolore porro unde possimus atque quaerat voluptates eius sit quod nostrum, expedita exercitationem aperiam sed odio at? Nobis ratione ipsum aspernatur, vel, odio libero expedita, architecto doloribus voluptate cumque suscipit perspiciatis hic? Recusandae fugiat quo suscipit perferendis, blanditiis nobis ducimus labore est excepturi corrupti quibusdam magnam dolorum aut? Libero, similique harum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde veritatis asperiores sint, nihil modi voluptatibus consequuntur porro blanditiis, nulla ullam dolorum alias. Libero, molestiae ullam culpa sint mollitia, exercitationem nemo, sunt autem aliquid obcaecati cupiditate inventore dolore eos. Expedita earum cum placeat adipisci odio molestiae cupiditate, sed, sequi obcaecati consectetur necessitatibus eligendi rerum accusantium? Illum, recusandae, non illo deleniti magni sed vero ducimus sint quibusdam et omnis repellat voluptate quod, explicabo aspernatur veritatis? Unde velit vitae adipisci fuga dolorum iusto expedita ullam animi et necessitatibus eveniet perspiciatis dolorem, impedit consequuntur voluptatum, qui nobis excepturi minima illo neque perferendis consectetur optio.</div>
        <div class=" w-96 bg-yellow-300">Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde veritatis asperiores sint, nihil modi voluptatibus consequuntur porro blanditiis, nulla ullam dolorum alias. Libero, molestiae ullam culpa sint mollitia, exercitationem nemo, sunt autem aliquid obcaecati cupiditate inventore dolore eos. Expedita earum cum placeat adipisci odio molestiae cupiditate, sed, sequi obcaecati consectetur necessitatibus eligendi rerum accusantium? Illum, recusandae, non illo deleniti magni sed vero ducimus sint quibusdam et omnis repellat voluptate quod, explicabo aspernatur veritatis? Unde velit vitae adipisci fuga dolorum iusto expedita ullam animi et necessitatibus eveniet perspiciatis dolorem, impedit consequuntur voluptatum, qui nobis excepturi minima illo neque perferendis consectetur optio.</div>
        <div class=" w-96 bg-green-300"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora quas soluta esse cupiditate et animi mollitia ratione error nesciunt exercitationem id iusto, reiciendis fuga molestias reprehenderit, architecto qui corrupti amet sit dolorum temporibus sint. Exercitationem animi accusantium explicabo! A, dicta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde veritatis asperiores sint, nihil modi voluptatibus consequuntur porro blanditiis, nulla ullam dolorum alias. Libero, molestiae ullam culpa sint mollitia, exercitationem nemo, sunt autem aliquid obcaecati cupiditate inventore dolore eos. Expedita earum cum placeat adipisci odio molestiae cupiditate, sed, sequi obcaecati consectetur necessitatibus eligendi rerum accusantium? Illum, recusandae, non illo deleniti magni sed vero ducimus sint quibusdam et omnis repellat voluptate quod, explicabo aspernatur veritatis? Unde velit vitae adipisci fuga dolorum iusto expedita ullam animi et necessitatibus eveniet perspiciatis dolorem, impedit consequuntur voluptatum, qui nobis excepturi minima illo neque perferendis consectetur optio.</div>
    </div>
</template>


<style  scoped>

</style>